rabbit1:
  image: rabbitmq-cluster
  hostname: rabbit1
  environment:
    - ERLANG_COOKIE=abcdefg
  ports:
    - "5672:5672"
    - "25672:25672"
    - "8080:15672"
#rabbit2:
#  image: rabbitmq-cluster-local
#  hostname: rabbit2
#  links:
#    - rabbit1
#  environment:
#    - ERLANG_COOKIE=abcdefg
#    - CLUSTER_WITH=rabbit1
#    - ENABLE_RAM=true
#  ports:
#    - "5673:5672"
#    - "15673:15672"
#rabbit3:
#  image: rabbitmq-cluster-local
#  hostname: rabbit3
#  links:
#    - rabbit1
#    - rabbit2
#  environment:
#    - ERLANG_COOKIE=abcdefg
#    - CLUSTER_WITH=rabbit1
#  ports:
#    - "5674:5672"
